import logging
import re
from dataclasses import dataclass
from urllib.parse import quote, unquote, urlsplit

import httpx
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.db.models import SimpleTabulationCode
from app.services.normalizer import CodeComponent


logger = logging.getLogger(__name__)

AUTO_DESCRIPTION_PREFIX = (
    "Auto-generated description. All this data was generated using "
    "https://github.com/filiperochalopes/ICD-11-code-normalizer."
)
AUTO_DESCRIPTION_TEMPLATE = (
    f"{AUTO_DESCRIPTION_PREFIX} This synonym was generated by the model: {{model_name}}"
)
WHO_ICD11_SOURCE_URL = "/orgs/WHO/sources/ICD-11-WHO/"
GROUPING_FALLBACK_COLUMNS = ("Grouping5", "Grouping4", "Grouping3", "Grouping2", "Grouping1")


@dataclass(slots=True)
class OCLConceptMetadata:
    extras: dict[str, object]
    first_stem_code: str | None = None


class OCLSyncService:
    def __init__(self, session: Session | None = None, client_factory=None) -> None:
        self._settings = get_settings()
        self._session = session
        self._client_factory = client_factory or httpx.Client

    def sync_concept_skeleton(
        self,
        normalized_code: str,
        title: str,
        components: list[CodeComponent] | None = None,
    ) -> bool:
        # Fast path: create concept + FSN + WHO mapping without waiting on the LLM.
        # Lets external consumers find the concept on OCL as soon as it has a
        # normalized code, instead of after AI phrase generation completes.
        if not self._is_configured():
            return False

        headers = self._build_headers()
        source_base_url = self._build_source_base_url()
        metadata = self._resolve_concept_metadata(components)

        try:
            with self._client_factory(timeout=30.0, follow_redirects=True) as client:
                self._sync_concept_and_fsn(
                    client=client,
                    source_base_url=source_base_url,
                    headers=headers,
                    normalized_code=normalized_code,
                    title=title,
                    metadata=metadata,
                )
                self._sync_primary_stem_mapping(
                    client=client,
                    source_base_url=source_base_url,
                    headers=headers,
                    normalized_code=normalized_code,
                    metadata=metadata,
                )
            return True
        except Exception:
            logger.exception(
                "OCL skeleton sync failed for normalized_code=%s", normalized_code
            )
            return False

    def sync_ai_enrichment(
        self,
        normalized_code: str,
        title: str,
        ai_phrase: str | None,
        ai_model_name: str | None = None,
    ) -> bool:
        if not self._is_configured():
            return False

        cleaned_ai_phrase = (ai_phrase or "").strip()
        if not cleaned_ai_phrase or cleaned_ai_phrase == title.strip():
            return False

        headers = self._build_headers()
        source_base_url = self._build_source_base_url()

        try:
            with self._client_factory(timeout=30.0, follow_redirects=True) as client:
                self._sync_ai_synonym_and_description(
                    client=client,
                    source_base_url=source_base_url,
                    headers=headers,
                    normalized_code=normalized_code,
                    ai_phrase=cleaned_ai_phrase,
                    ai_model_name=ai_model_name,
                )
            return True
        except Exception:
            logger.exception(
                "OCL enrichment sync failed for normalized_code=%s", normalized_code
            )
            return False

    def sync_normalized_result(
        self,
        normalized_code: str,
        title: str,
        ai_phrase: str | None = None,
        ai_model_name: str | None = None,
        components: list[CodeComponent] | None = None,
    ) -> bool:
        if not self._is_configured():
            return False

        headers = self._build_headers()
        source_base_url = self._build_source_base_url()
        metadata = self._resolve_concept_metadata(components)

        try:
            with self._client_factory(timeout=30.0, follow_redirects=True) as client:
                self._sync_concept_and_fsn(
                    client=client,
                    source_base_url=source_base_url,
                    headers=headers,
                    normalized_code=normalized_code,
                    title=title,
                    metadata=metadata,
                )
                self._sync_ai_synonym_and_description(
                    client=client,
                    source_base_url=source_base_url,
                    headers=headers,
                    normalized_code=normalized_code,
                    ai_phrase=(ai_phrase or "").strip() if ai_phrase else "",
                    ai_model_name=ai_model_name,
                    title=title,
                )
                self._sync_primary_stem_mapping(
                    client=client,
                    source_base_url=source_base_url,
                    headers=headers,
                    normalized_code=normalized_code,
                    metadata=metadata,
                )
            return True
        except Exception:
            logger.exception("OCL sync failed for normalized_code=%s", normalized_code)
            return False

    def _is_configured(self) -> bool:
        if not self._settings.ocl_token.strip() or not self._settings.ocl_lookup_source.strip():
            logger.info(
                "Skipping OCL sync because OCL_TOKEN or OCL_LOOKUP_SOURCE is not configured"
            )
            return False
        return True

    def _build_headers(self) -> dict[str, str]:
        return {"Authorization": f"Token {self._settings.ocl_token.strip()}"}

    def _sync_concept_and_fsn(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
        title: str,
        metadata: OCLConceptMetadata,
    ) -> None:
        concept = self._get_concept(client, source_base_url, headers, normalized_code)
        if concept is None:
            self._create_concept(
                client=client,
                source_base_url=source_base_url,
                headers=headers,
                normalized_code=normalized_code,
                title=title,
                metadata=metadata,
            )
        else:
            self._update_concept_if_needed(
                client=client,
                source_base_url=source_base_url,
                headers=headers,
                normalized_code=normalized_code,
                concept=concept,
                metadata=metadata,
            )

        names = self._list_names(client, source_base_url, headers, normalized_code)
        self._upsert_fully_specified_name(
            client=client,
            source_base_url=source_base_url,
            headers=headers,
            normalized_code=normalized_code,
            names=names,
            title=title,
        )

    def _sync_ai_synonym_and_description(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
        ai_phrase: str,
        ai_model_name: str | None,
        title: str | None = None,
    ) -> None:
        cleaned_ai_phrase = ai_phrase.strip() if ai_phrase else ""
        if not cleaned_ai_phrase:
            return
        if title is not None and cleaned_ai_phrase == title.strip():
            return

        names = self._list_names(client, source_base_url, headers, normalized_code)
        self._upsert_ai_synonym(
            client=client,
            source_base_url=source_base_url,
            headers=headers,
            normalized_code=normalized_code,
            names=names,
            ai_phrase=cleaned_ai_phrase,
        )

        descriptions = self._list_descriptions(
            client,
            source_base_url,
            headers,
            normalized_code,
        )
        self._upsert_description(
            client=client,
            source_base_url=source_base_url,
            headers=headers,
            normalized_code=normalized_code,
            descriptions=descriptions,
            model_name=ai_model_name or self._settings.openrouter_model,
        )

    def _sync_primary_stem_mapping(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
        metadata: OCLConceptMetadata,
    ) -> None:
        if not metadata.first_stem_code:
            return

        mappings = self._list_mappings(
            client,
            source_base_url,
            headers,
            normalized_code,
        )
        self._upsert_primary_stem_mapping(
            client=client,
            source_base_url=source_base_url,
            headers=headers,
            normalized_code=normalized_code,
            mappings=mappings,
            first_stem_code=metadata.first_stem_code,
        )

    def _get_concept(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
    ) -> dict | None:
        response = client.get(
            self._concept_endpoint_url(source_base_url, normalized_code),
            headers=headers,
        )
        if response.status_code == 404:
            return None
        response.raise_for_status()
        payload = response.json()
        if isinstance(payload, dict):
            return payload
        return {}

    def _create_concept(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
        title: str,
        metadata: OCLConceptMetadata,
    ) -> None:
        payload = {
            "id": normalized_code,
            "retired": False,
            **self._concept_payload(metadata),
            "names": [self._fully_specified_payload(title)],
        }
        response = client.post(f"{source_base_url}/concepts/", json=payload, headers=headers)
        if response.status_code not in {200, 201, 409}:
            response.raise_for_status()

    def _update_concept_if_needed(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
        concept: dict,
        metadata: OCLConceptMetadata,
    ) -> None:
        payload = self._concept_payload(metadata, concept.get("extras"))
        if self._concept_matches(concept, payload):
            return

        client.patch(
            self._concept_endpoint_url(source_base_url, normalized_code),
            json=payload,
            headers=headers,
        ).raise_for_status()

    def _list_names(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
    ) -> list[dict]:
        response = client.get(
            f"{self._concept_endpoint_url(source_base_url, normalized_code)}names/",
            headers=headers,
        )
        if response.status_code == 404:
            return []
        response.raise_for_status()
        return self._extract_results(response.json())

    def _list_descriptions(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
    ) -> list[dict]:
        response = client.get(
            f"{self._concept_endpoint_url(source_base_url, normalized_code)}descriptions/",
            headers=headers,
        )
        if response.status_code == 404:
            return []
        response.raise_for_status()
        return self._extract_results(response.json())

    def _list_mappings(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
    ) -> list[dict]:
        response = client.get(
            f"{self._concept_endpoint_url(source_base_url, normalized_code)}mappings/",
            headers=headers,
        )
        if response.status_code == 404:
            return []
        response.raise_for_status()
        return self._extract_results(response.json())

    def _upsert_fully_specified_name(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
        names: list[dict],
        title: str,
    ) -> None:
        payload = self._fully_specified_payload(title)
        existing = self._find_fully_specified_name(names)
        if existing is None:
            client.post(
                f"{self._concept_endpoint_url(source_base_url, normalized_code)}names/",
                json=payload,
                headers=headers,
            ).raise_for_status()
            return

        if self._name_matches(existing, payload):
            return

        client.patch(
            f"{self._concept_endpoint_url(source_base_url, normalized_code)}names/{existing['uuid']}/",
            json=payload,
            headers=headers,
        ).raise_for_status()

    def _upsert_ai_synonym(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
        names: list[dict],
        ai_phrase: str,
    ) -> None:
        payload = self._synonym_payload(ai_phrase)
        existing = self._find_ai_synonym_name(names)
        if existing is None:
            client.post(
                f"{self._concept_endpoint_url(source_base_url, normalized_code)}names/",
                json=payload,
                headers=headers,
            ).raise_for_status()
            return

        if self._name_matches(existing, payload):
            return

        client.patch(
            f"{self._concept_endpoint_url(source_base_url, normalized_code)}names/{existing['uuid']}/",
            json=payload,
            headers=headers,
        ).raise_for_status()

    def _upsert_description(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
        descriptions: list[dict],
        model_name: str,
    ) -> None:
        payload = self._description_payload(model_name)
        existing = self._find_auto_generated_description(descriptions)
        if existing is None:
            client.post(
                f"{self._concept_endpoint_url(source_base_url, normalized_code)}descriptions/",
                json=payload,
                headers=headers,
            ).raise_for_status()
            return

        if self._description_matches(existing, payload):
            return

        client.patch(
            (
                f"{self._concept_endpoint_url(source_base_url, normalized_code)}"
                f"descriptions/{existing['uuid']}/"
            ),
            json=payload,
            headers=headers,
        ).raise_for_status()

    def _upsert_primary_stem_mapping(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
        mappings: list[dict],
        first_stem_code: str,
    ) -> None:
        payload = self._mapping_payload(source_base_url, normalized_code, first_stem_code)
        existing = self._find_primary_stem_mapping(mappings, first_stem_code)
        if existing is None:
            response = client.post(
                f"{source_base_url}/mappings/",
                json=payload,
                headers=headers,
            )
            if response.status_code not in {200, 201, 409}:
                response.raise_for_status()
            return

        if self._mapping_matches(existing, payload):
            return

        client.patch(
            self._mapping_detail_url(source_base_url, existing),
            json=payload,
            headers=headers,
        ).raise_for_status()

    def _build_source_base_url(self) -> str:
        source = self._settings.ocl_lookup_source.strip()
        if source.startswith("http://") or source.startswith("https://"):
            return source.rstrip("/")

        normalized_source = source if source.startswith("/") else f"/{source}"
        return f"{self._settings.ocl_base_url.rstrip('/')}{normalized_source.rstrip('/')}"

    @staticmethod
    def _extract_results(payload) -> list[dict]:
        if isinstance(payload, list):
            return payload
        if isinstance(payload, dict):
            results = payload.get("results")
            if isinstance(results, list):
                return results
        return []

    def _resolve_concept_metadata(
        self,
        components: list[CodeComponent] | None,
    ) -> OCLConceptMetadata:
        # Business rule:
        # OCL metadata and the WHO mapping are always anchored on the first stem
        # code of the already-normalized expression. Extensions never drive chapter,
        # block, or WHO concept mapping metadata.
        first_stem_code = self._find_first_stem_code(components)
        extras: dict[str, object] = {"isLeaf": self._is_leaf_stem_code(first_stem_code)}
        first_stem_row = self._lookup_code_row(first_stem_code)
        if first_stem_row is None:
            return OCLConceptMetadata(extras=extras, first_stem_code=first_stem_code)

        raw_row = self._raw_row_dict(first_stem_row)

        for field_name in (
            "Foundation URI",
            "Linearization URI",
            "DepthInKind",
            "IsResidual",
            "BrowserLink",
        ):
            self._set_extra_if_present(extras, field_name, raw_row.get(field_name))

        chapter_no = self._clean_metadata_value(raw_row.get("ChapterNo") or first_stem_row.chapter_or_group)
        if chapter_no is not None:
            extras["ChapterNo"] = chapter_no

        block_id = self._resolve_block_id(first_stem_row)
        if block_id is not None:
            extras["BlockId"] = block_id

        return OCLConceptMetadata(extras=extras, first_stem_code=first_stem_code)

    @staticmethod
    def _find_first_stem_code(components: list[CodeComponent] | None) -> str | None:
        if not components:
            return None

        for component in components:
            if component.is_stem:
                return component.code
        return components[0].code

    def _lookup_code_row(self, code: str | None) -> SimpleTabulationCode | None:
        if self._session is None or not code:
            return None
        return self._session.scalar(
            select(SimpleTabulationCode).where(SimpleTabulationCode.code == code)
        )

    def _is_leaf_stem_code(self, code: str | None) -> bool:
        # A stem code is a leaf in the ICD-11 hierarchy when no other tabulation
        # row points to it as its ``parent_code``. The WHO Simple Tabulation
        # spreadsheet has no explicit ``IsLeaf`` column, so this children-lookup
        # is the only signal available here.
        if self._session is None or not code:
            return True
        child_id = self._session.scalar(
            select(SimpleTabulationCode.id)
            .where(SimpleTabulationCode.parent_code == code)
            .limit(1)
        )
        return child_id is None

    def _resolve_block_id(self, row: SimpleTabulationCode) -> str | None:
        direct_block_id = self._clean_metadata_value(self._raw_row_dict(row).get("BlockId"))
        if direct_block_id is not None:
            return direct_block_id

        parent_block_id = self._resolve_parent_block_id(row)
        if parent_block_id is not None:
            return parent_block_id

        return self._resolve_grouping_block_id(row)

    def _resolve_parent_block_id(self, row: SimpleTabulationCode) -> str | None:
        if self._session is None:
            return None

        visited_codes = {row.code}
        parent_code = row.parent_code

        while parent_code:
            if parent_code in visited_codes:
                break
            visited_codes.add(parent_code)

            parent_row = self._lookup_code_row(parent_code)
            if parent_row is None:
                break

            parent_raw = self._raw_row_dict(parent_row)
            parent_block_id = self._clean_metadata_value(parent_raw.get("BlockId"))
            if parent_block_id is not None:
                return parent_block_id

            class_kind = self._normalize_name_marker(parent_raw.get("ClassKind"))
            if class_kind == "block":
                return self._clean_metadata_value(parent_row.code)

            parent_code = parent_row.parent_code

        return None

    def _resolve_grouping_block_id(self, row: SimpleTabulationCode) -> str | None:
        raw_row = self._raw_row_dict(row)
        for grouping_column in GROUPING_FALLBACK_COLUMNS:
            grouping_value = self._clean_metadata_value(raw_row.get(grouping_column))
            if grouping_value is not None:
                return grouping_value
        return None

    @staticmethod
    def _raw_row_dict(row: SimpleTabulationCode) -> dict[str, object]:
        return row.raw_row_json if isinstance(row.raw_row_json, dict) else {}

    @staticmethod
    def _set_extra_if_present(extras: dict[str, object], key: str, value: object) -> None:
        cleaned_value = OCLSyncService._clean_metadata_value(value)
        if cleaned_value is not None:
            extras[key] = cleaned_value

    @staticmethod
    def _clean_metadata_value(value: object) -> str | None:
        if value is None:
            return None

        text = str(value).strip()
        if not text:
            return None
        if text.lower() in {"none", "nan", "null"}:
            return None
        return text

    @staticmethod
    def _concept_payload(
        metadata: OCLConceptMetadata,
        existing_extras: dict[str, object] | object | None = None,
    ) -> dict[str, object]:
        merged_extras = {}
        if isinstance(existing_extras, dict):
            merged_extras.update(existing_extras)
        merged_extras.update(metadata.extras)
        return {
            "concept_class": "Diagnosis",
            "datatype": "N/A",
            "extras": merged_extras,
        }

    @staticmethod
    def _normalize_name_marker(value: object) -> str:
        return re.sub(r"[^a-z0-9]+", "", str(value or "").lower())

    def _find_fully_specified_name(self, names: list[dict]) -> dict | None:
        for name in names:
            marker = self._normalize_name_marker(name.get("name_type"))
            if marker == "fullyspecified":
                return name

        for name in names:
            marker = self._normalize_name_marker(name.get("type"))
            if marker == "fullyspecified":
                return name

        for name in names:
            if name.get("locale") == "en" and name.get("locale_preferred") is True:
                return name

        return None

    def _find_ai_synonym_name(self, names: list[dict]) -> dict | None:
        for name in names:
            if name.get("locale") != "en":
                continue
            if name.get("locale_preferred") is True:
                continue
            if self._normalize_name_marker(name.get("name_type")) == "fullyspecified":
                continue
            if self._normalize_name_marker(name.get("type")) == "fullyspecified":
                continue
            return name
        return None

    @staticmethod
    def _find_auto_generated_description(descriptions: list[dict]) -> dict | None:
        for description in descriptions:
            if description.get("locale") != "en":
                continue
            text = str(description.get("description") or "")
            if text.startswith(AUTO_DESCRIPTION_PREFIX):
                return description
        return None

    def _find_primary_stem_mapping(
        self,
        mappings: list[dict],
        first_stem_code: str,
    ) -> dict | None:
        exact_match: dict | None = None
        fallback_match: dict | None = None

        for mapping in mappings:
            if self._normalize_name_marker(mapping.get("map_type")) != "narrowerthan":
                continue

            target_source_url = self._mapping_target_source_url(mapping)
            if target_source_url != self._normalize_relative_url(WHO_ICD11_SOURCE_URL):
                continue

            target_code = self._mapping_target_code(mapping)
            if target_code == first_stem_code:
                exact_match = mapping
                break

            if fallback_match is None:
                fallback_match = mapping

        return exact_match or fallback_match

    @staticmethod
    def _fully_specified_payload(title: str) -> dict:
        return {
            "name": title,
            "locale": "en",
            "locale_preferred": True,
            "name_type": "FULLY_SPECIFIED",
        }

    @staticmethod
    def _synonym_payload(ai_phrase: str) -> dict:
        # OCL rejects blank/null name_type on the names endpoint. For synonyms the
        # field must be omitted entirely and the API will persist it as null.
        return {
            "name": ai_phrase,
            "locale": "en",
            "locale_preferred": False,
        }

    @staticmethod
    def _description_payload(model_name: str) -> dict:
        return {
            "description": AUTO_DESCRIPTION_TEMPLATE.format(model_name=model_name),
            "locale": "en",
            "locale_preferred": False,
        }

    def _mapping_payload(
        self,
        source_base_url: str,
        normalized_code: str,
        first_stem_code: str,
    ) -> dict[str, str]:
        source_relative_url = self._normalize_relative_url(source_base_url)
        if source_relative_url is None:
            raise RuntimeError("Unable to resolve relative OCL source URL for mapping sync.")

        return {
            "map_type": "NARROWER-THAN",
            "from_concept_url": self._concept_reference_url(source_relative_url, normalized_code),
            "to_concept_url": self._who_concept_url(first_stem_code),
        }

    @staticmethod
    def _name_matches(existing: dict, payload: dict) -> bool:
        return (
            existing.get("name") == payload["name"]
            and existing.get("locale") == payload["locale"]
            and existing.get("locale_preferred") == payload["locale_preferred"]
            and (existing.get("name_type") or "") == (payload.get("name_type") or "")
        )

    @staticmethod
    def _description_matches(existing: dict, payload: dict) -> bool:
        return (
            existing.get("description") == payload["description"]
            and existing.get("locale") == payload["locale"]
            and existing.get("locale_preferred") == payload["locale_preferred"]
        )

    def _mapping_matches(self, existing: dict, payload: dict[str, str]) -> bool:
        return (
            self._normalize_name_marker(existing.get("map_type"))
            == self._normalize_name_marker(payload["map_type"])
            and self._normalize_relative_url(existing.get("from_concept_url"))
            == self._normalize_relative_url(payload["from_concept_url"])
            and self._mapping_target_source_url(existing)
            == self._mapping_target_source_url(payload)
            and self._mapping_target_code(existing) == self._mapping_target_code(payload)
        )

    @staticmethod
    def _concept_matches(existing: dict, payload: dict[str, object]) -> bool:
        existing_extras = existing.get("extras")
        if not isinstance(existing_extras, dict):
            existing_extras = {}

        payload_extras = payload.get("extras")
        if not isinstance(payload_extras, dict):
            payload_extras = {}

        managed_extras_match = all(
            existing_extras.get(key) == value for key, value in payload_extras.items()
        )

        return (
            existing.get("concept_class") == payload["concept_class"]
            and existing.get("datatype") == payload["datatype"]
            and managed_extras_match
        )

    def _mapping_target_source_url(self, mapping: dict[str, object]) -> str | None:
        direct_source_url = self._normalize_relative_url(mapping.get("to_source_url"))
        if direct_source_url is not None:
            return direct_source_url

        return self._source_url_from_concept_url(mapping.get("to_concept_url"))

    def _mapping_target_code(self, mapping: dict[str, object]) -> str | None:
        direct_code = self._clean_metadata_value(mapping.get("to_concept_code"))
        if direct_code is not None:
            return direct_code

        concept_url = mapping.get("to_concept_url")
        if not isinstance(concept_url, str) or "/concepts/" not in concept_url:
            return None

        encoded_code = concept_url.rstrip("/").split("/concepts/")[-1]
        return unquote(encoded_code)

    def _mapping_detail_url(self, source_base_url: str, mapping: dict[str, object]) -> str:
        raw_url = mapping.get("url")
        if isinstance(raw_url, str) and raw_url.strip():
            return self._absolute_api_url(raw_url)

        mapping_id = self._clean_metadata_value(mapping.get("id")) or self._clean_metadata_value(
            mapping.get("uuid")
        )
        if mapping_id is None:
            raise RuntimeError("Unable to resolve mapping detail URL for OCL sync.")
        return f"{source_base_url}/mappings/{quote(mapping_id, safe='')}/"

    def _absolute_api_url(self, url: str) -> str:
        if url.startswith("http://") or url.startswith("https://"):
            return url
        base = self._settings.ocl_base_url.rstrip("/")
        return f"{base}/{url.lstrip('/')}"

    @staticmethod
    def _normalize_relative_url(url: object) -> str | None:
        if not isinstance(url, str):
            return None

        text = url.strip()
        if not text:
            return None

        parsed = urlsplit(text)
        normalized = parsed.path if parsed.scheme or parsed.netloc else text
        normalized = normalized if normalized.startswith("/") else f"/{normalized}"
        normalized = normalized.rstrip("/")
        return f"{normalized}/"

    def _source_url_from_concept_url(self, concept_url: object) -> str | None:
        normalized = self._normalize_relative_url(concept_url)
        if normalized is None or "/concepts/" not in normalized:
            return None
        return f"{normalized.split('/concepts/')[0]}/"

    @staticmethod
    def _concept_endpoint_url(source_base_url: str, normalized_code: str) -> str:
        # Concept mnemonics that contain "/" must be double-encoded when used in
        # the HTTP path segment, even though OCL stores the canonical concept URL
        # with only one layer of encoding.
        encoded_code = quote(quote(normalized_code, safe=""), safe="")
        return f"{source_base_url.rstrip('/')}/concepts/{encoded_code}/"

    @staticmethod
    def _concept_reference_url(source_base_url: str, normalized_code: str) -> str:
        encoded_code = quote(normalized_code, safe="")
        return f"{source_base_url.rstrip('/')}/concepts/{encoded_code}/"

    @staticmethod
    def _who_concept_url(code: str) -> str:
        return f"{WHO_ICD11_SOURCE_URL}concepts/{quote(code, safe='')}/"
