import logging
import re
from urllib.parse import quote

import httpx

from app.core.config import get_settings


logger = logging.getLogger(__name__)

AUTO_DESCRIPTION_PREFIX = (
    "Auto-generated description. All this data was generated using "
    "https://github.com/filiperochalopes/ICD-11-code-normalizer."
)
AUTO_DESCRIPTION_TEMPLATE = (
    f"{AUTO_DESCRIPTION_PREFIX} This synonym was generated by the model: {{model_name}}"
)


class OCLSyncService:
    def __init__(self, client_factory=None) -> None:
        self._settings = get_settings()
        self._client_factory = client_factory or httpx.Client

    def sync_normalized_result(
        self,
        normalized_code: str,
        title: str,
        ai_phrase: str | None = None,
        ai_model_name: str | None = None,
    ) -> bool:
        if not self._settings.ocl_token.strip() or not self._settings.ocl_lookup_source.strip():
            logger.info("Skipping OCL sync because OCL_TOKEN or OCL_LOOKUP_SOURCE is not configured")
            return False

        headers = {"Authorization": f"Token {self._settings.ocl_token.strip()}"}
        source_base_url = self._build_source_base_url()

        try:
            with self._client_factory(timeout=30.0, follow_redirects=True) as client:
                if not self._concept_exists(client, source_base_url, headers, normalized_code):
                    self._create_concept(
                        client=client,
                        source_base_url=source_base_url,
                        headers=headers,
                        normalized_code=normalized_code,
                        title=title,
                    )

                names = self._list_names(client, source_base_url, headers, normalized_code)
                self._upsert_fully_specified_name(
                    client=client,
                    source_base_url=source_base_url,
                    headers=headers,
                    normalized_code=normalized_code,
                    names=names,
                    title=title,
                )

                cleaned_ai_phrase = (ai_phrase or "").strip()
                if cleaned_ai_phrase and cleaned_ai_phrase != title.strip():
                    names = self._list_names(client, source_base_url, headers, normalized_code)
                    self._upsert_ai_synonym(
                        client=client,
                        source_base_url=source_base_url,
                        headers=headers,
                        normalized_code=normalized_code,
                        names=names,
                        ai_phrase=cleaned_ai_phrase,
                    )

                    descriptions = self._list_descriptions(
                        client,
                        source_base_url,
                        headers,
                        normalized_code,
                    )
                    self._upsert_description(
                        client=client,
                        source_base_url=source_base_url,
                        headers=headers,
                        normalized_code=normalized_code,
                        descriptions=descriptions,
                        model_name=ai_model_name or self._settings.openrouter_model,
                    )
            return True
        except Exception:
            logger.exception("OCL sync failed for normalized_code=%s", normalized_code)
            return False

    def _concept_exists(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
    ) -> bool:
        response = client.get(self._concept_url(source_base_url, normalized_code), headers=headers)
        if response.status_code == 404:
            return False
        response.raise_for_status()
        return True

    def _create_concept(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
        title: str,
    ) -> None:
        payload = {
            "id": normalized_code,
            "concept_class": "Diagnosis",
            "datatype": "N/A",
            "retired": False,
            "names": [self._fully_specified_payload(title)],
        }
        response = client.post(f"{source_base_url}/concepts/", json=payload, headers=headers)
        if response.status_code not in {200, 201, 409}:
            response.raise_for_status()

    def _list_names(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
    ) -> list[dict]:
        response = client.get(
            f"{self._concept_url(source_base_url, normalized_code)}/names/",
            headers=headers,
        )
        if response.status_code == 404:
            return []
        response.raise_for_status()
        return self._extract_results(response.json())

    def _list_descriptions(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
    ) -> list[dict]:
        response = client.get(
            f"{self._concept_url(source_base_url, normalized_code)}/descriptions/",
            headers=headers,
        )
        if response.status_code == 404:
            return []
        response.raise_for_status()
        return self._extract_results(response.json())

    def _upsert_fully_specified_name(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
        names: list[dict],
        title: str,
    ) -> None:
        payload = self._fully_specified_payload(title)
        existing = self._find_fully_specified_name(names)
        if existing is None:
            client.post(
                f"{self._concept_url(source_base_url, normalized_code)}/names/",
                json=payload,
                headers=headers,
            ).raise_for_status()
            return

        if self._name_matches(existing, payload):
            return

        client.patch(
            f"{self._concept_url(source_base_url, normalized_code)}/names/{existing['uuid']}/",
            json=payload,
            headers=headers,
        ).raise_for_status()

    def _upsert_ai_synonym(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
        names: list[dict],
        ai_phrase: str,
    ) -> None:
        payload = self._synonym_payload(ai_phrase)
        existing = self._find_ai_synonym_name(names)
        if existing is None:
            client.post(
                f"{self._concept_url(source_base_url, normalized_code)}/names/",
                json=payload,
                headers=headers,
            ).raise_for_status()
            return

        if self._name_matches(existing, payload):
            return

        client.patch(
            f"{self._concept_url(source_base_url, normalized_code)}/names/{existing['uuid']}/",
            json=payload,
            headers=headers,
        ).raise_for_status()

    def _upsert_description(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
        descriptions: list[dict],
        model_name: str,
    ) -> None:
        payload = self._description_payload(model_name)
        existing = self._find_auto_generated_description(descriptions)
        if existing is None:
            client.post(
                f"{self._concept_url(source_base_url, normalized_code)}/descriptions/",
                json=payload,
                headers=headers,
            ).raise_for_status()
            return

        if self._description_matches(existing, payload):
            return

        client.patch(
            (
                f"{self._concept_url(source_base_url, normalized_code)}/"
                f"descriptions/{existing['uuid']}/"
            ),
            json=payload,
            headers=headers,
        ).raise_for_status()

    def _build_source_base_url(self) -> str:
        source = self._settings.ocl_lookup_source.strip()
        if source.startswith("http://") or source.startswith("https://"):
            return source.rstrip("/")

        normalized_source = source if source.startswith("/") else f"/{source}"
        return f"{self._settings.ocl_base_url.rstrip('/')}{normalized_source.rstrip('/')}"

    @staticmethod
    def _extract_results(payload) -> list[dict]:
        if isinstance(payload, list):
            return payload
        if isinstance(payload, dict):
            results = payload.get("results")
            if isinstance(results, list):
                return results
        return []

    @staticmethod
    def _normalize_name_marker(value: str | None) -> str:
        return re.sub(r"[^a-z0-9]+", "", (value or "").lower())

    def _find_fully_specified_name(self, names: list[dict]) -> dict | None:
        for name in names:
            marker = self._normalize_name_marker(name.get("name_type"))
            if marker == "fullyspecified":
                return name

        for name in names:
            marker = self._normalize_name_marker(name.get("type"))
            if marker == "fullyspecified":
                return name

        for name in names:
            if name.get("locale") == "en" and name.get("locale_preferred") is True:
                return name

        return None

    def _find_ai_synonym_name(self, names: list[dict]) -> dict | None:
        for name in names:
            if name.get("locale") != "en":
                continue
            if name.get("locale_preferred") is True:
                continue
            if self._normalize_name_marker(name.get("name_type")) == "fullyspecified":
                continue
            if self._normalize_name_marker(name.get("type")) == "fullyspecified":
                continue
            return name
        return None

    @staticmethod
    def _find_auto_generated_description(descriptions: list[dict]) -> dict | None:
        for description in descriptions:
            if description.get("locale") != "en":
                continue
            text = str(description.get("description") or "")
            if text.startswith(AUTO_DESCRIPTION_PREFIX):
                return description
        return None

    @staticmethod
    def _fully_specified_payload(title: str) -> dict:
        return {
            "name": title,
            "locale": "en",
            "locale_preferred": True,
            "name_type": "FULLY_SPECIFIED",
        }

    @staticmethod
    def _synonym_payload(ai_phrase: str) -> dict:
        return {
            "name": ai_phrase,
            "locale": "en",
            "locale_preferred": False,
            "name_type": None,
        }

    @staticmethod
    def _description_payload(model_name: str) -> dict:
        return {
            "description": AUTO_DESCRIPTION_TEMPLATE.format(model_name=model_name),
            "locale": "en",
            "locale_preferred": False,
        }

    @staticmethod
    def _name_matches(existing: dict, payload: dict) -> bool:
        return (
            existing.get("name") == payload["name"]
            and existing.get("locale") == payload["locale"]
            and existing.get("locale_preferred") == payload["locale_preferred"]
            and existing.get("name_type") == payload.get("name_type")
        )

    @staticmethod
    def _description_matches(existing: dict, payload: dict) -> bool:
        return (
            existing.get("description") == payload["description"]
            and existing.get("locale") == payload["locale"]
            and existing.get("locale_preferred") == payload["locale_preferred"]
        )

    @staticmethod
    def _concept_url(source_base_url: str, normalized_code: str) -> str:
        return f"{source_base_url}/concepts/{quote(normalized_code, safe='')}"
