import logging
import re
from dataclasses import dataclass
from urllib.parse import quote

import httpx
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.db.models import SimpleTabulationCode
from app.services.normalizer import CodeComponent


logger = logging.getLogger(__name__)

AUTO_DESCRIPTION_PREFIX = (
    "Auto-generated description. All this data was generated using "
    "https://github.com/filiperochalopes/ICD-11-code-normalizer."
)
AUTO_DESCRIPTION_TEMPLATE = (
    f"{AUTO_DESCRIPTION_PREFIX} This synonym was generated by the model: {{model_name}}"
)


@dataclass(slots=True)
class OCLConceptMetadata:
    extras: dict[str, object]


class OCLSyncService:
    def __init__(self, session: Session | None = None, client_factory=None) -> None:
        self._settings = get_settings()
        self._session = session
        self._client_factory = client_factory or httpx.Client

    def sync_normalized_result(
        self,
        normalized_code: str,
        title: str,
        ai_phrase: str | None = None,
        ai_model_name: str | None = None,
        components: list[CodeComponent] | None = None,
    ) -> bool:
        if not self._settings.ocl_token.strip() or not self._settings.ocl_lookup_source.strip():
            logger.info("Skipping OCL sync because OCL_TOKEN or OCL_LOOKUP_SOURCE is not configured")
            return False

        headers = {"Authorization": f"Token {self._settings.ocl_token.strip()}"}
        source_base_url = self._build_source_base_url()
        metadata = self._resolve_concept_metadata(components)

        try:
            with self._client_factory(timeout=30.0, follow_redirects=True) as client:
                concept = self._get_concept(client, source_base_url, headers, normalized_code)
                if concept is None:
                    self._create_concept(
                        client=client,
                        source_base_url=source_base_url,
                        headers=headers,
                        normalized_code=normalized_code,
                        title=title,
                        metadata=metadata,
                    )
                else:
                    self._update_concept_if_needed(
                        client=client,
                        source_base_url=source_base_url,
                        headers=headers,
                        normalized_code=normalized_code,
                        concept=concept,
                        metadata=metadata,
                    )

                names = self._list_names(client, source_base_url, headers, normalized_code)
                self._upsert_fully_specified_name(
                    client=client,
                    source_base_url=source_base_url,
                    headers=headers,
                    normalized_code=normalized_code,
                    names=names,
                    title=title,
                )

                cleaned_ai_phrase = (ai_phrase or "").strip()
                if cleaned_ai_phrase and cleaned_ai_phrase != title.strip():
                    names = self._list_names(client, source_base_url, headers, normalized_code)
                    self._upsert_ai_synonym(
                        client=client,
                        source_base_url=source_base_url,
                        headers=headers,
                        normalized_code=normalized_code,
                        names=names,
                        ai_phrase=cleaned_ai_phrase,
                    )

                    descriptions = self._list_descriptions(
                        client,
                        source_base_url,
                        headers,
                        normalized_code,
                    )
                    self._upsert_description(
                        client=client,
                        source_base_url=source_base_url,
                        headers=headers,
                        normalized_code=normalized_code,
                        descriptions=descriptions,
                        model_name=ai_model_name or self._settings.openrouter_model,
                    )
            return True
        except Exception:
            logger.exception("OCL sync failed for normalized_code=%s", normalized_code)
            return False

    def _get_concept(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
    ) -> dict | None:
        response = client.get(self._concept_url(source_base_url, normalized_code), headers=headers)
        if response.status_code == 404:
            return None
        response.raise_for_status()
        payload = response.json()
        if isinstance(payload, dict):
            return payload
        return {}

    def _create_concept(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
        title: str,
        metadata: OCLConceptMetadata,
    ) -> None:
        payload = {
            "id": normalized_code,
            "retired": False,
            **self._concept_payload(metadata),
            "names": [self._fully_specified_payload(title)],
        }
        response = client.post(f"{source_base_url}/concepts/", json=payload, headers=headers)
        if response.status_code not in {200, 201, 409}:
            response.raise_for_status()

    def _update_concept_if_needed(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
        concept: dict,
        metadata: OCLConceptMetadata,
    ) -> None:
        payload = self._concept_payload(metadata, concept.get("extras"))
        if self._concept_matches(concept, payload):
            return

        client.patch(
            self._concept_url(source_base_url, normalized_code),
            json=payload,
            headers=headers,
        ).raise_for_status()

    def _list_names(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
    ) -> list[dict]:
        response = client.get(
            f"{self._concept_url(source_base_url, normalized_code)}/names/",
            headers=headers,
        )
        if response.status_code == 404:
            return []
        response.raise_for_status()
        return self._extract_results(response.json())

    def _list_descriptions(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
    ) -> list[dict]:
        response = client.get(
            f"{self._concept_url(source_base_url, normalized_code)}/descriptions/",
            headers=headers,
        )
        if response.status_code == 404:
            return []
        response.raise_for_status()
        return self._extract_results(response.json())

    def _upsert_fully_specified_name(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
        names: list[dict],
        title: str,
    ) -> None:
        payload = self._fully_specified_payload(title)
        existing = self._find_fully_specified_name(names)
        if existing is None:
            client.post(
                f"{self._concept_url(source_base_url, normalized_code)}/names/",
                json=payload,
                headers=headers,
            ).raise_for_status()
            return

        if self._name_matches(existing, payload):
            return

        client.patch(
            f"{self._concept_url(source_base_url, normalized_code)}/names/{existing['uuid']}/",
            json=payload,
            headers=headers,
        ).raise_for_status()

    def _upsert_ai_synonym(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
        names: list[dict],
        ai_phrase: str,
    ) -> None:
        payload = self._synonym_payload(ai_phrase)
        existing = self._find_ai_synonym_name(names)
        if existing is None:
            client.post(
                f"{self._concept_url(source_base_url, normalized_code)}/names/",
                json=payload,
                headers=headers,
            ).raise_for_status()
            return

        if self._name_matches(existing, payload):
            return

        client.patch(
            f"{self._concept_url(source_base_url, normalized_code)}/names/{existing['uuid']}/",
            json=payload,
            headers=headers,
        ).raise_for_status()

    def _upsert_description(
        self,
        client: httpx.Client,
        source_base_url: str,
        headers: dict[str, str],
        normalized_code: str,
        descriptions: list[dict],
        model_name: str,
    ) -> None:
        payload = self._description_payload(model_name)
        existing = self._find_auto_generated_description(descriptions)
        if existing is None:
            client.post(
                f"{self._concept_url(source_base_url, normalized_code)}/descriptions/",
                json=payload,
                headers=headers,
            ).raise_for_status()
            return

        if self._description_matches(existing, payload):
            return

        client.patch(
            (
                f"{self._concept_url(source_base_url, normalized_code)}/"
                f"descriptions/{existing['uuid']}/"
            ),
            json=payload,
            headers=headers,
        ).raise_for_status()

    def _build_source_base_url(self) -> str:
        source = self._settings.ocl_lookup_source.strip()
        if source.startswith("http://") or source.startswith("https://"):
            return source.rstrip("/")

        normalized_source = source if source.startswith("/") else f"/{source}"
        return f"{self._settings.ocl_base_url.rstrip('/')}{normalized_source.rstrip('/')}"

    @staticmethod
    def _extract_results(payload) -> list[dict]:
        if isinstance(payload, list):
            return payload
        if isinstance(payload, dict):
            results = payload.get("results")
            if isinstance(results, list):
                return results
        return []

    def _resolve_concept_metadata(
        self,
        components: list[CodeComponent] | None,
    ) -> OCLConceptMetadata:
        extras: dict[str, object] = {"isLeaf": True}
        first_stem_row = self._find_first_stem_row(components)
        if first_stem_row is None:
            return OCLConceptMetadata(extras=extras)

        chapter_no = self._clean_metadata_value(
            first_stem_row.raw_row_json.get("ChapterNo")
            or first_stem_row.chapter_or_group
        )
        if chapter_no is not None:
            extras["ChapterNo"] = chapter_no

        block_id = self._resolve_block_id(first_stem_row)
        if block_id is not None:
            extras["BlockId"] = block_id

        return OCLConceptMetadata(extras=extras)

    def _find_first_stem_row(
        self,
        components: list[CodeComponent] | None,
    ) -> SimpleTabulationCode | None:
        if self._session is None or not components:
            return None

        first_stem_code = None
        for component in components:
            if component.is_stem:
                first_stem_code = component.code
                break

        if first_stem_code is None:
            first_stem_code = components[0].code if components else None
        if first_stem_code is None:
            return None

        return self._session.scalar(
            select(SimpleTabulationCode).where(SimpleTabulationCode.code == first_stem_code)
        )

    def _resolve_block_id(self, row: SimpleTabulationCode) -> str | None:
        direct_block_id = self._clean_metadata_value(row.raw_row_json.get("BlockId"))
        if direct_block_id is not None:
            return direct_block_id

        if self._session is None:
            return None

        visited_codes = {row.code}
        parent_code = row.parent_code

        while parent_code:
            if parent_code in visited_codes:
                break
            visited_codes.add(parent_code)

            parent_row = self._session.scalar(
                select(SimpleTabulationCode).where(SimpleTabulationCode.code == parent_code)
            )
            if parent_row is None:
                break

            class_kind = self._normalize_name_marker(parent_row.raw_row_json.get("ClassKind"))
            if class_kind == "block":
                return self._clean_metadata_value(parent_row.code)

            parent_code = parent_row.parent_code

        return None

    @staticmethod
    def _clean_metadata_value(value: object) -> str | None:
        if value is None:
            return None

        text = str(value).strip()
        if not text:
            return None
        if text.lower() in {"none", "nan", "null"}:
            return None
        return text

    @staticmethod
    def _concept_payload(
        metadata: OCLConceptMetadata,
        existing_extras: dict[str, object] | object | None = None,
    ) -> dict[str, object]:
        merged_extras = {}
        if isinstance(existing_extras, dict):
            merged_extras.update(existing_extras)
        merged_extras.update(metadata.extras)
        return {
            "concept_class": "Diagnosis",
            "datatype": "N/A",
            "extras": merged_extras,
        }

    @staticmethod
    def _normalize_name_marker(value: str | None) -> str:
        return re.sub(r"[^a-z0-9]+", "", (value or "").lower())

    def _find_fully_specified_name(self, names: list[dict]) -> dict | None:
        for name in names:
            marker = self._normalize_name_marker(name.get("name_type"))
            if marker == "fullyspecified":
                return name

        for name in names:
            marker = self._normalize_name_marker(name.get("type"))
            if marker == "fullyspecified":
                return name

        for name in names:
            if name.get("locale") == "en" and name.get("locale_preferred") is True:
                return name

        return None

    def _find_ai_synonym_name(self, names: list[dict]) -> dict | None:
        for name in names:
            if name.get("locale") != "en":
                continue
            if name.get("locale_preferred") is True:
                continue
            if self._normalize_name_marker(name.get("name_type")) == "fullyspecified":
                continue
            if self._normalize_name_marker(name.get("type")) == "fullyspecified":
                continue
            return name
        return None

    @staticmethod
    def _find_auto_generated_description(descriptions: list[dict]) -> dict | None:
        for description in descriptions:
            if description.get("locale") != "en":
                continue
            text = str(description.get("description") or "")
            if text.startswith(AUTO_DESCRIPTION_PREFIX):
                return description
        return None

    @staticmethod
    def _fully_specified_payload(title: str) -> dict:
        return {
            "name": title,
            "locale": "en",
            "locale_preferred": True,
            "name_type": "FULLY_SPECIFIED",
        }

    @staticmethod
    def _synonym_payload(ai_phrase: str) -> dict:
        return {
            "name": ai_phrase,
            "locale": "en",
            "locale_preferred": False,
            "name_type": None,
        }

    @staticmethod
    def _description_payload(model_name: str) -> dict:
        return {
            "description": AUTO_DESCRIPTION_TEMPLATE.format(model_name=model_name),
            "locale": "en",
            "locale_preferred": False,
        }

    @staticmethod
    def _name_matches(existing: dict, payload: dict) -> bool:
        return (
            existing.get("name") == payload["name"]
            and existing.get("locale") == payload["locale"]
            and existing.get("locale_preferred") == payload["locale_preferred"]
            and existing.get("name_type") == payload.get("name_type")
        )

    @staticmethod
    def _description_matches(existing: dict, payload: dict) -> bool:
        return (
            existing.get("description") == payload["description"]
            and existing.get("locale") == payload["locale"]
            and existing.get("locale_preferred") == payload["locale_preferred"]
        )

    @staticmethod
    def _concept_matches(existing: dict, payload: dict[str, object]) -> bool:
        existing_extras = existing.get("extras")
        if not isinstance(existing_extras, dict):
            existing_extras = {}

        payload_extras = payload.get("extras")
        if not isinstance(payload_extras, dict):
            payload_extras = {}

        managed_extras_match = all(
            existing_extras.get(key) == value for key, value in payload_extras.items()
        )

        return (
            existing.get("concept_class") == payload["concept_class"]
            and existing.get("datatype") == payload["datatype"]
            and managed_extras_match
        )

    @staticmethod
    def _concept_url(source_base_url: str, normalized_code: str) -> str:
        return f"{source_base_url}/concepts/{quote(normalized_code, safe='')}"
